### ISSUE TITLE
Is the Wishart mechanism (and the LinearRegression model built on top of it) really private?

### ISSUE THREAD

**Issue by ftramer** [IBM/differential-privacy-library#23]
The documentation of the Wishart mechanism references the paper "Symmetric matrix perturbation for differentially-private principal component analysis" by Imtiaz and Sarwate.

Yet, two subsequent papers (at least) note that the analysis of this mechanism is incorrect and that it does not in fact guarantee differential privacy:

- Footnote 4 of http://proceedings.mlr.press/v98/sheffet19a/sheffet19a.pdf, which references a different work by Jiang et al.  that proposed the same mechanism
- Section 1.2. of http://papers.nips.cc/paper/9567-differentially-private-covariance-estimation.pdf, which claims that the mechanism of Jiang et al. / Imtiaz and Sarwate is not private.

For some linear regression applications, I've tried replacing the Wishart noise with Laplace noise (as proposed in https://arxiv.org/pdf/1705.10829.pdf), and got consistently worse results, thus further suggesting that the noise added by the Wishart mechanism may be too optimistic.

**Comment by naoise-h** [comment]
Dear Florian,

Thank you for bringing this to our attention, we were not aware of it until now. We will review the literature as a matter of urgency. Feel free to contribute your own alternative solution with a Pull Request if you have one to hand.

Best wishes,
Naoise.

**Comment by naoise-h** [comment]
Hi Florian,
I have opened PR #25 that resolves this issue. Your feedback on that PR would be much appreciated.

**Comment by ftramer** [comment]
Hi,

Thanks for following up on this!
I'm not familiar with the work of Amin et al. so I can't give an expert
opinion on this change.
One thing I could suggest is to check whether the logistic regression and
linear regression mechanisms give "comparable" results for some toy
classification tasks. From the theory at least, I think that either should
perform roughly the same so if there's huge discrepancies between the two
there might be a problem.
