### ISSUE TITLE
Differential Private Percentiles

### ISSUE THREAD

**Issue by nadavaviv** [IBM/differential-privacy-library#26]
Hi,
I would like to know if there is any future planning to support differentially private percentile calculations, or is there a current implementation that can be used?

Thanks

**Comment by naoise-h** [comment]
Hi there,

There is no implementation at present in diffprivlib, but something we are hoping to add soon. If you have any implementations of interest, feel free to add them here for future reference.

**Comment by nadavaviv** [comment]
Sorry in advance if being a bit rude, but do you have an estimation on when this will be implemented?

**Comment by naoise-h** [comment]
Differentially private quantile, percentile and median functions were added in PR #30 .

**Comment by nadavaviv** [comment]
Awesome!
Thank you!!
When are you planning on releasing it? 😬

**Comment by naoise-h** [comment]
It should be released next month. However, you can start using it straight away by cloning this repository, and running `pip install .` from that directory.

**Comment by nadavaviv** [comment]
Great, Thank you :)
