### ISSUE TITLE
Random Number Generation

### ISSUE THREAD

**Issue by michaelpatrickpurcell** [IBM/differential-privacy-library#27]
It looks like the default numpy RNG is being used to generate random values in the primitive mechanisms (e.g. the Laplace mechanism and its derivatives).  As Aaron Roth et al. point out in their recent paper [Guidelines for Implementing and Auditing Differentially Private Systems (Section 5.1)](https://arxiv.org/abs/2002.04049):

> “Random numbers” should be generated by a cryptographically secure pseudo-random number generator (CSPRNG). Mersenne Twister is a commonly used pseudo-random number generator for statistical applications (in many libraries, it is the default) but is considered insecure for differential privacy.

The [secrets module](https://docs.python.org/3/library/secrets.html)  (described in detail in [PEP 506](https://www.python.org/dev/peps/pep-0506/)) makes it relatively easy to access such sources of randomness in a system-agnostic way. Would it be possible to either change the default RNG used in this module or add an option that allows a user to specify which RNG they would like to use? 

For what it's worth, the following snippet is a minimal working example of some code that can be used to generate samples from the Uniform(0,1) distribution via the secrets module:
```python
import secrets

def gen_unifs(n):
  rng = secrets.SystemRandom()
  unifs = [rng.uniform(0,1) for _ in range(n)]
  return unifs
```

In fact, the secrets module isn't really necessary here.  The same functionality can be achieved via the random module:
```python
import random

def gen_unifs2(n):
  rng = random.SystemRandom()
  unifs = [rng.uniform(0,1) for _ in range(n)]
  return unifs
```

The secrets module may, however, provide other functions that make it easier and/or cleaner to securely generate large numbers of random samples efficiently.

**Comment by naoise-h** [comment]
Hi Michael,

Thanks for bringing this to attention. We had actually planned to revamp the random number generation in diffprivlib as part of the refactoring of the `mechanisms` module (#17). Our initial plan was to upgrade to the new RNG in numpy, which allows us to specify the `BitGenerator`, but it doesn't seem there is a crypto-secure `BitGenerator` shipped by numpy at present.

Using numpy's `random` module is desirable to give us direct access to various probability distributions with ease. Are you familiar with numpy's `BitGenerator`, and possibly using the `secrets` package in conjunction with this?
