### ISSUE TITLE
Bug of LinearRegression

### ISSUE THREAD

**Issue by MichaelYangg** [IBM/differential-privacy-library#34]
There is a bug at `line 115` of the `/diffprivlib/models/linear_regression.py`

```Python
95 def _construct_regression_obj(X, y, bounds_X, bounds_y, epsilon, alpha):
          ...
114    for i in range(n_targets):
115        sensitivity = np.abs(bounds_y[i]).max() ** 2
```

The `bounds_y` here is a `tuple` of size 2.
I guess this perhaps meant to be `bounds_y[0][i], bounds_y[1][i]`.

Here is the output of the 

![image](https://user-images.githubusercontent.com/50360179/104279417-3a762f80-54e5-11eb-9861-10a3f91e1887.png)

![image](https://user-images.githubusercontent.com/50360179/104279444-47931e80-54e5-11eb-913e-23cea10e56da.png)

![image](https://user-images.githubusercontent.com/50360179/104279573-7f01cb00-54e5-11eb-85f4-7bce7a5b9659.png)

**Comment by naoise-h** [comment]
Hi Michael, thanks for bringing this bug to our attention. I notice your PR #35  which fixes this. We greatly appreciate your help!
