### ISSUE TITLE
how to generate a noisy vector?

### ISSUE THREAD

**Issue by hwj-wik** [IBM/differential-privacy-library#39]
https://github.com/IBM/differential-privacy-library/blob/4d48efb6d6086c57d1b813b76b2755c87735d5d8/diffprivlib/mechanisms/vector.py#L154
why you create the noisy vector by line 154 rather than line150?
https://github.com/IBM/differential-privacy-library/blob/4d48efb6d6086c57d1b813b76b2755c87735d5d8/diffprivlib/mechanisms/vector.py#L150

**Comment by naoise-h** [comment]
The first declaration in line 150 produces a standard normal vector, but we want to specify the norm of the vector as a sample from a gamma distribution. Therefore, you can look at line 150 as deciding the direction of the vector, and line 154 fixes the magnitude of the vector.

**Comment by hwj-wik** [comment]
So, if we want to produces a Laplace vector. Can we just change the gamma distribution to a Laplace distribution?

**Comment by naoise-h** [comment]
If you want to generate a vector of Laplace noise, it's best to use an instance of the Laplace mechanism. E.g., you can generate a vector of length 10 as follows:
```python
from diffprivlib.mechanisms import Laplace
lap = Laplace(epsilon=1, sensitivity=1)
vec = [lap.randomise(0) for i in range(10)]
```

**Comment by hwj-wik** [comment]
Thank you!
