### ISSUE TITLE
Wishart mechanism should be removed as non-private

### ISSUE THREAD

**Issue by ahonkela** [IBM/differential-privacy-library#42]
It seems diffprivlib still includes code and documentation for the Wishart mechanism which is known to be invalid. This was apparently previously addressed for linear regression in #23 and #25, but the invalid mechanism is still part of the code and listed in the documentation without any warnings.

**Comment by naoise-h** [comment]
Hi Antti, Yes you are of course correct. We have deprecated the mechanism, but in hindsight it should have been removed in the previous release. This will be fixed in the next release later this year.

Thanks, Naoise.
