### ISSUE TITLE
percentile function raises a RuntimeError when given a list of identical values

### ISSUE THREAD

**Issue by nadavaviv** [IBM/differential-privacy-library#43]
Hi, 

I've come across this issue (At least I think it's an issue)
When I try to calculate a percentile over a list of data which contains only one value (regardless of the number of occurrences it has), a `RuntimeError` will be raised with the following message:
```
RuntimeError: Can't find a candidate to return. Debugging info: Rand: <Random number between 0 and 1), Probabilities: [nan, nan, nan, (Depends on the length of the list)]
```

Is this behaviour expected?
If so, if there's a workaround or maybe a flag I can pass to the function to receive anything other than an error?

Thank you :)

**Comment by naoise-h** [comment]
Hi there,

Thanks for finding this bug. We will investigate this and let you know when we derive a solution.

Thanks, Naoise.

**Comment by nadavaviv** [comment]
Thanks for the update :)

BTW, I've found another case where this issue arises...
If you try to use it with this
