### ISSUE TITLE
Upper Bound of _var() in diffprivlib/tools/utils.py

### ISSUE THREAD

**Issue by justanotherlad** [IBM/differential-privacy-library#44]
Line **422** of **diffprivlib/tools/utils.py** sets the output of  `_var()` function as: 
`output = np.minimum(dp_mech.randomise(actual_var), (upper - lower) ** 2)`

This basically means, the upper bound of variance is set to `(upper - lower) ** 2` .

However, [Popoviciu's inequality](https://en.wikipedia.org/wiki/Popoviciu%27s_inequality_on_variances) on variances states that `var<= ((upper - lower) ** 2)/4` .

Is there a reason we are avoiding this division by a factor of 4, or is this a bug?

During one of my runs, I got the differentially private variance as **54.3917**, whereas the actual variance was **9.1667**. 
This seems a little off, with too much noise added. 
Perhaps we can set the upper bound as `((upper - lower) ** 2)/4` with the guarantees from Popoviciu's inequality?

If this is a bug, I can send a PR to fix this. Awaiting response. Thanks!

 ##
![Screenshot from 2021-07-01 14-38-32](https://user-images.githubusercontent.com/31207633/124159169-75324b00-dab8-11eb-902c-3cd650a7ac5c.png)

**Comment by naoise-h** [comment]
Hi, thanks for this observation! You're correct.

We would be delighted if you were to submit a PR to fix this. Let us know if you have any questions.

Thanks, Naoise.

**Comment by justanotherlad** [comment]
Created a PR #45 
Thank you!
