### ISSUE TITLE
ML Support

### ISSUE THREAD

**Issue by Hiramdu** [IBM/differential-privacy-library#57]
I only see several ml algorithms in the example. May I know do you support other tree base algorithms such as XGBoost?

**Comment by vikramsh2002** [comment]
Yes, you can use Boosting algorithms in trees but the chances of overfitting increase you must need to keep in mind that these types of algorithms very easily go towards Overfitting specially XGBOOST RandonForestClassifier, etc.

**Comment by Hiramdu** [comment]
> Yes, you can use Boosting algorithms in trees but the chances of overfitting increase you must need to keep in mind that these types of algorithms very easily go towards Overfitting specially XGBOOST RandonForestClassifier, etc.

But I cannot find xgboost in the model directory. How should I use XGBoost and your method
<img width="1677" alt="Screen Shot 2021-11-13 at 3 49 31 PM" src="https://user-images.githubusercontent.com/19141771/141658714-23358fab-f85b-435b-bdf0-2a57daa396e8.png">
?

**Comment by naoise-h** [comment]
Hi, we currently don't have support for XGBoost with DP. It may be something we will consider adding in the future. The best place to learn about current functionality is in our documentation: https://diffprivlib.readthedocs.io/
