### ISSUE TITLE
Meaning of bounds.

### ISSUE THREAD

**Issue by BismeetSingh** [IBM/differential-privacy-library#58]
I understand what epsilon is but how do bounds affect the model?

**Comment by naoise-h** [comment]
In differential privacy, we add noise proportional to the spread of the data to privatise it. The bounds gives the model the information it needs to calculate the spread of the data and calibrate the noise accordingly.

**Comment by BismeetSingh** [comment]
How do we calculate these bounds?

**Comment by naoise-h** [comment]
To preserve differential privacy, this needs to be done using knowledge of the domain of the data (i.e., without looking at the data itself). If this is not possible, then the bounds can be calculated on the data itself  (even though this is a violation of differential privacy). To calculate the bounds on a dataset `X`, you can use `bounds=(np.min(X, axis=0), np.max(X, axis=0))`.
