### ISSUE TITLE
random forest bug

### ISSUE THREAD

**Issue by Hiramdu** [IBM/differential-privacy-library#59]
Hi, when I test random forest on a  small dataset using your library, no any response for 1 day already. May you help test or check?
<img width="1421" alt="Screen Shot 2021-11-25 at 7 00 04 PM" src="https://user-images.githubusercontent.com/19141771/143508937-6ed5cf4a-87ee-4109-bd3f-67c89a925043.png">
?

**Comment by naoise-h** [comment]
Hi, can you try the same code on a different dataset? Without seeing the dataset it's difficult to say what the problem is.

**Comment by Hiramdu** [comment]
> Hi, can you try the same code on a different dataset? Without seeing the dataset it's difficult to say what the problem is.

Hi, I used your dataset in other examples, but still the same issue. May you help test on it and give an example too?
X_train = np.loadtxt("https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",
                        usecols=(0, 4, 10, 11, 12), delimiter=", ")

y_train = np.loadtxt("https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",
                        usecols=14, dtype=str, delimiter=", ")

X_test = np.loadtxt("https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test",
                        usecols=(0, 4, 10, 11, 12), delimiter=", ", skiprows=1)

y_test = np.loadtxt("https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test",
                        usecols=14, dtype=str, delimiter=", ", skiprows=1)

**Comment by Hiramdu** [comment]
> Hi, can you try the same code on a different dataset? Without seeing the dataset it's difficult to say what the problem is.

I tried on the dataset you used in other examples, it could have a result. But it's accuracy is 0. Very puzzled.

**Comment by Hiramdu** [comment]
> > Hi, can you try the same code on a different dataset? Without seeing the dataset it's difficult to say what the problem is.
> 
> I tried on the dataset you used in other examples(adult.data), it could have a result. But it's very puzzled on my dataset.

**Comment by naoise-h** [comment]
Can you try running the algorithm for a period of time (say 60 seconds), stop the operation, and then print out `dprf.__dict__`? The output of this may help find the problem if you can post it here.
