### ISSUE TITLE
DP Random Forest Performance Issues

### ISSUE THREAD

**Issue by jan0b** [IBM/differential-privacy-library#64]
# **Describe the bug**
I encountered two issues while using the diffprivlib random forest classifier:

1) I want to compare the influence of epsilon on the performance of a dp random forest classifier with a non-dp random forest classifier.  For the non-dp random forest I use sci-kit learn's RandomForestClassifier. The issue is, that even for extremly high epsilons (100 to 10.000) the diffprivlib random forest does not approximate the sci-kit random forests performance.

2) The diffprivlib random forest takes very long to train even when setting _'n_jobs=-1'_. The sci-kit random forest trains for about 13/15s whereas the diffprivlib random forest trains for about 25/30 min. Shouldn't both trainings take about the same time?

# **To Reproduce**
Please find my code below to reproduce the described behaviour. I use the Kaggle dataset from here: https://www.kaggle.com/datasets/sulianova/cardiovascular-disease-dataset

```
# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import diffprivlib as dpl

from sklearn import ensemble
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import preprocessing

# Data handling
dataset = pd.read_csv('../cardio_train.csv', sep=';')
dataset.head()

X_raw = dataset.drop(['id', 'cardio'], axis=1)
X_raw_cat = X_raw.drop(['age', 'height', 'weight', 'ap_hi', 'ap_lo'], axis=1)
X_raw_cont = X_raw[['age', 'height', 'weight', 'ap_hi', 'ap_lo']]
y_raw = dataset['cardio']

normalize = preprocessing.StandardScaler()
ordinal = preprocessing.OrdinalEncoder()

X_cont = normalize.fit_transform(X_raw_cont)
X_cat = ordinal.fit_transform(X_raw_cat)

X = np.concatenate([X_cont, X_cat], axis=1)
y = y_raw

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Non-DP RF
model = ensemble.RandomForestClassifier(n_estimators=1000, oob_score=True, n_jobs=-1, random_state=1302)
model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)
y_train_pred_oob = np.argmax(model.oob_decision_function_, axis=1)
y_test_pred = model.predict(X_test)

# DP RF
epsilon = 10000.0
model_dp = dpl.models.RandomForestClassifier(n_estimators=1000, epsilon=epsilon, n_jobs=-1).fit(X_train, y_train)

y_dp_train_pred = model_dp.predict(X_train)
y_dp_test_pred = model_dp.predict(X_test)

# Comparison
print(
metrics.accuracy_score(y_train, y_train_pred),
model.oob_score_,
metrics.accuracy_score(y_test, y_test_pred),
metrics.accuracy_score(y_train, y_dp_train_pred),
metrics.accuracy_score(y_test, y_dp_test_pred))
```

# **Expected behavior**
The expected behaviour would be the dp-model approximating the non-dp models performance for high epsilons.

# **Screenshots**
The models training times:
<img width="1491" alt="Bildschirmfoto 2022-05-05 um 16 25 33" src="https://user-images.githubusercontent.com/98087792/166945465-53da5f16-4f5a-4072-aff1-9945c5de310f.png">

The models performances:
<img width="1489" alt="Bildschirmfoto 2022-05-05 um 16 26 28" src="https://user-images.githubusercontent.com/98087792/166945495-dd31761e-01df-4cb0-9ff6-e2b9c197d1db.png">

# **System information:**
 - Linux 4.18.0 (x86-64)
 - Python 3.8.12
 - numpy 1.21.2
 - pandas 1.2.3
 - diffprivlib 0.5.1
 - sklearn 1.0.2

**Comment by Zeyu-Shen** [comment]
I also encountered this problem. Four months ago dp random forest seemed to work correctly.

**Comment by roijalbaker** [comment]
I also encounter these issues. I also noticed memory usage explodes compared to SKLearn forests and is not comparable with the increase of memory use (e.g.) from SKLearn to DiffPrivLib LogisticRegression.
