### ISSUE TITLE
nanmean is broken

### ISSUE THREAD

**Issue by marty90** [IBM/differential-privacy-library#87]
**Describe the bug**

The `nan*` functions do not work due to a bug in the bound calculation
At this [line](https://github.com/IBM/differential-privacy-library/blob/92eeeec4f377df8857956699c317904994b56f4b/diffprivlib/tools/utils.py#L279C9-L279C15), bounds are erroneously set to `nan`.
Thus, at [this](https://github.com/IBM/differential-privacy-library/blob/92eeeec4f377df8857956699c317904994b56f4b/diffprivlib/validation.py#L191C8-L191C41) line, the condition becomes False, as `np.allclose` returns `False` by default with `nan`.
This makes [this](https://github.com/IBM/differential-privacy-library/blob/92eeeec4f377df8857956699c317904994b56f4b/diffprivlib/validation.py#L195) exception to trigger erroneously.

To fix: replace `np.min` and `np.max` with `np.nanmin` and `np.nanmax`

**To Reproduce**

Just run the code:
```python
diffprivlib.tools.nanmean(np.array([0,1,2,3,4, np.nan]))
```

It raises:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/diffprivlib/tools/utils.py", line 267, in nanmean
    return _mean(array, epsilon=epsilon, bounds=bounds, axis=axis, dtype=dtype, keepdims=keepdims,
  File "/usr/local/lib/python3.8/dist-packages/diffprivlib/tools/utils.py", line 290, in _mean
    array = clip_to_bounds(np.ravel(array), bounds)
  File "/usr/local/lib/python3.8/dist-packages/diffprivlib/validation.py", line 195, in clip_to_bounds
    raise ValueError(f"For non-scalar bounds, input array must be 2-dimensional. Got {array.ndim} dimensions.")
ValueError: For non-scalar bounds, input array must be 2-dimensional. Got 1 dimensions.
```

**Comment by naoise-h** [comment]
Thank you for the bug report Martino. This is indeed a bug. We will push a fix for this in due course. Many thanks for finding and reporting it.
