### ISSUE TITLE
can We use These Library With Flowers federated learning framework for Apply Dp With Fedrating learning 

### ISSUE THREAD

**Issue by ibad321** [IBM/differential-privacy-library#96]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - OS
 - Python version
 - diffprivlib version or commit number
 - numpy / scikit-learn version

**Comment by naoise-h** [comment]
Diffprivlib isn't natively set up to work with federated learning frameworks, but you could certainly use some its functionality to develop your own applications with Flower.
